import sbt._
import Keys._
import play.Project._
import com.typesafe.sbteclipse.core.EclipsePlugin.EclipseKeys

object ApplicationBuild extends Build {

	val appName    = "petstore-client"
	val appVersion = "1.2.3"
	
	val appDependencies = Seq(
		"com.hibu" %% "play2-bragger" % "1.2.3",
		javaCore,
		javaJdbc,
		javaEbean
	)
	
	lazy val play2Bragger = ProjectRef(file("../../../../modules/play2-bragger"), "play2-bragger")
	
	lazy val main = play.Project(appName, appVersion, appDependencies).settings(
	  
	    //braggerClients += "http://localhost:9000/api-docs.wsdl/pet" 
	      
		// adding to the project sources the autogenerated code for calling the petstore api 
		unmanagedSourceDirectories in Compile <+= baseDirectory( _ / "codegen" / "src" ), 
		unmanagedSourceDirectories in Test <+= baseDirectory( _ / "codegen" / "test" ),
		
		// bragger repo
		resolvers in ThisBuild += "github pages repo" at "http://yelllabs.github.com/bragger",
		// easywsdl
		resolvers in ThisBuild += "petalslink" at "http://maven.petalslink.com/public",

		// sbt eclipse
		EclipseKeys.skipParents in ThisBuild:= false,
		EclipseKeys.withSource in ThisBuild := true

	).dependsOn(
		//play2Bragger
	).aggregate(
		//play2Bragger
	)
	
}
