import sbt._
import Keys._
import play.Project._
import com.typesafe.sbteclipse.core.EclipsePlugin.EclipseKeys

object ApplicationBuild extends Build {

	val appName         = "petstore-client"
	val appVersion      = "1.2.3-SNAPSHOT"
	
	val appDependencies = Seq(
		//"com.hibu" % "play2-bragger" % "1.2.3-SNAPSHOT",
		javaCore,
		javaJdbc,
		javaEbean
	)
	
	lazy val play2Bragger = ProjectRef(file("../../../../modules/play2-bragger"), "play2-bragger")
	
	lazy val main = play.Project(appName, appVersion, appDependencies).settings(
	  
		// adding to the project sources the autogenerated code for calling the petstore api 
		unmanagedSourceDirectories in Compile <+= baseDirectory( _ / "codegen" / "src" ),		
		// TODO generated test sources???
		
		// bragger repo
		resolvers in ThisBuild += "github pages repo" at "http://yelllabs.github.com/bragger",
		// easywsdl
		resolvers in ThisBuild += "petalslink" at "http://maven.petalslink.com/public",

		// with these lines, the 'play eclipse' command adds automatically the source folders to the porject
		// remove these when getting the linked modules as managed dependencies
		// put here an entry for each element specified in the dependsOn (directly or recursively across all the subprojects)
		//unmanagedSourceDirectories in Compile <+= baseDirectory( _ / "linked-modules" / "bragger-core" / "src" / "main" / "java" ),
		//unmanagedSourceDirectories in Compile <+= baseDirectory( _ / "linked-modules" / "play2-bragger" / "app"),
		
		// sbt eclipse
		EclipseKeys.withSource in ThisBuild := true, 
		EclipseKeys.skipParents in ThisBuild:= false

	).dependsOn(
		play2Bragger
	).aggregate(
		play2Bragger
	)

		
//	lazy val play2Bragger = play.Project("play2-bragger", appVersion, 
//		Seq(
//			//"com.hibu" % "bragger-core" % appVersion exclude("com.wordnik", "swagger-core_2.9.1"), // comment out this line if dependsOn include bragger
//			"com.wordnik" %% "swagger-play2" % "1.2.1.hibu-SNAPSHOT",                                // comment out this line if dependsOn include bragger
//			"org.ow2.easywsdl" % "easywsdl-tool-java2wsdl" % "2.3",
//			"org.slf4j" % "slf4j-api" % "1.7.2"
//		), 
//		path = file("./linked-modules/play2-bragger")
//	).settings(
//	    // avoid eclipsify the subproject if aggregate is used on the parent project
//		EclipseKeys.skipProject := true
//	).dependsOn(
//	    braggerCore
//	).aggregate(
//	    braggerCore
//	)
	
}
